spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://groupadd-eureka:8761/eureka
---
spring:
  profiles: eng
hello:
  message: Hello World!
---
spring:
  profiles: kor
hello:
  message: 안녕!