spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itsbysean/spring-boot-study.git
          search-paths: config-repo
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ['bus-refresh']
server:
  port: 8888